#!/bin/sh
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

TERM=xterm-256color
LS_COLORS='rs=0:di=01;34:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:tw=30;42:ow=34;42:st=37;44:ex=01;32:';
PERL_DESTRUCT_LEVEL=2
export PERL_DESTRUCT_LEVEL
export LS_COLORS
export PATH="${PATH}:$HOME/.local/bin"
export TERMINAL=urxvt
export ARCHFLAGS="-arch x86_64"
export EDITOR=nano
export VISUAL=nano
export AWT_TOOLKIT=MToolkit
export MSF_DATABASE_CONFIG="$HOME/.msf4/database.yml"
export RXVT_SOCKET="$HOME/.urxvt/urxvtd-`hostname`"
export XDG_RUNTIME_DIR="/run/user/$UID"
export DBUS_SESSION_BUS_ADDRESS="unix:path=${XDG_RUNTIME_DIR}/bus"

(sleep 1s && feh --bg-fill ~/Pictures/wallpaper/wallpaperbetter.jpg) &
(sleep 2s && picom --config ~/.config/picom/picom.conf) &
(sleep 3s && urxvtd) &
(sleep 4s && sxhkd -c ~/.config/sxhkd/sxhkdrc) &
(sleep 5s && redshift-gtk) &
(sleep 6s && nm-applet --sm-disable) &
(sleep 7s && blueman-applet) &
(sleep 8s && unclutter -root) &
(sleep 9s && dunst) &
(sleep 10s && xautolock -time 60 -locker blurlock) &
[ ! -s ~/.config/mpd/pid ] && mpd &

eval $(ssh-agent)

session=${1:-dwm}
case $session in
    i3                ) exec i3;;
    awesome           ) exec awesome;;
    dwm               ) while true; do
    dwm 2> ~/.dwm.log
done;;
    *                 ) exec $1;;
esac
