#!/bin/sh
set -e
daemon=${1:?}
state="%{F#FF5555}off%{F-}"
cmd="$(systemctl status $daemon | grep -i run 2>/dev/null || echo '')"

[[ "$cmd" ]] && state="%{F#BFBFBF}on%{F-}"

echo "%{F#BD93F9}${daemon}%{F-} ${state}"
exit 0